version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: structure/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend